### ISSUE TITLE
How to feature flag effectively

### ISSUE THREAD

**Issue by benfreke** [Brisbane-Laravel-Meetup/meetups#13]
What is feature flagging? What problems does it solve? When should you use it? When should you not use it?

**Comment by gregskerman** [comment]
_effectively_ is a big call my friend! not sure I can live up to that expectation!

But yes, I'm happy to build something out to discuss the benefits and pitfalls, and show an example of how to get Laravel using a 3rd party tool such as LaunchDarkly.

**Comment by jryd** [comment]
A recording of this talk can be found here; https://youtu.be/sMYmZjfqPN0?t=277
