### ISSUE TITLE
Talk Proposal: Modern HTTP Caching

### ISSUE THREAD

**Issue by rhysemmerson** [Brisbane-Laravel-Meetup/meetups#15]
By leveraging modern standards based http caching you can avoid littering your code with calls to the cache facade and more efficiently utilise the client side cache.

* Cover `stale-while-revalidate` and `stale-if-error`
* How to add caching to http clients
* How to add caching headers to api responses
* How to customise caching client side

**Comment by gregskerman** [comment]
yes! We should go ahead and just schedule this one I think :)
