### ISSUE TITLE
Talk Proposal: WordPress for Laravel Developers

### ISSUE THREAD

**Issue by samlev** [Brisbane-Laravel-Meetup/meetups#16]
I've given this talk before at the Brisbane PHP Meetup in 2019 and at the 2020 international PHP conference, but seeing as the Laravel Meetup has a different audience I figure that I'll offer it here, too.

This talk is an exploration of everyone's "favourite" legacy system, and how to inject an air of modern development... by injecting a modern framework into WordPress as a theme.

**Comment by jryd** [comment]
I'm both intrigued and alarmed at the same time.

I've heard of it being done, but not seen it in action.

Sounds like a great talk!
