### ISSUE TITLE
Talk Request: What's New in Laravel 8

### ISSUE THREAD

**Issue by benfreke** [Brisbane-Laravel-Meetup/meetups#4]
I think it'd be a great idea to run a session on the new things, or also just someone sharing their upgrade experience

**Comment by gregskerman** [comment]
A few of our systems will be upgrading as soon as 8 stabilises a bit. iSeekplant could run this talk in a pinch, but this would be a fantastic opportunity for someone who wants to talk but is struggling to find something to talk about.

**Comment by benfreke** [comment]
I'm going to close this as 8 has been out for a while.
