### ISSUE TITLE
PHPStorm, XDebug and Docker

### ISSUE THREAD

**Issue by benfreke** [Brisbane-Laravel-Meetup/meetups#5]
XDebug is awesome. While I wouldn't go so far as to say that you're an amateur if you don't use it, my opinion is very close to that.

I've created a repeatable and easy to use setup that I've been using for a while now, and if there's enough interest I'm happy to give a talk about a dockerised workflow simplified Xdebug usage within PhpStorm.

**Comment by jryd** [comment]
This sounds interesting; I'm always interested in workflow improvements.

Not being a heavy XDebug user, I'd be curious to see your setup and some use cases/walkthroughs of it being used in action.

It'd also be a nice non-Laravel, satellite talk.

How long would you need for the talk? We've got a couple of spots for ~15 minute talks at the next meetup if you can fit it into that time frame? If you need longer then we can see what other suggestions come through and possibly look at allocating more time. Failing that, we can always save it for a bigger talk at the meetup after next.

**Comment by benfreke** [comment]
I can do this in 15 minutes I'm sure. I'll get it put together properly soon and get a rough estimate. I'm thinking about 10 minutes should smash it out and then it's 5 minutes for questions.

**Comment by jryd** [comment]
Ok, great.

Let me know once you've had a chance to put it together and get a better estimate and we can finalise everything.

Thanks @benfreke !

**Comment by benfreke** [comment]
If it helps for the first meetup, I can guarantee to keep it under 15 minutes? 

I'm already avoiding a deep dive into the internals of Docker Compose and I'll just cut out the stuff about XDebug cache grind. As useful as those are, they're out of scope of what I want to present for this talk.

**Comment by jryd** [comment]
Sounds good to me!

Let's lock it in then.

I'll be in touch closer to the event to firm up timings etc.

Thanks Ben!
