### ISSUE TITLE
Talk Proposal: Data Transfer Objects, Value Objects, and Eloquent Custom Casts

### ISSUE THREAD

**Issue by jessarcher** [Brisbane-Laravel-Meetup/meetups#7]
I recently wrote a popular blog post on [casting JSON columns to DTOs/value objects with Eloquent](https://jessarcher.com/blog/casting-json-columns-to-value-objects/). I thought it might be useful to do a talk on this same topic as it was a pretty satisfying solution to a problem I've often come across, an evidently many others have as well.

My plan would be to cover some use cases for DTOs and value objects and then walk through the process of casting to them from the database. As with my blog post, I would probably step through the different options for working with JSON columns in Laravel, continually refactoring and streamlining the code along the way.

* https://jessarcher.com/blog/casting-json-columns-to-value-objects/
* https://github.com/jessarcher/laravel-castable-data-transfer-object
* https://laravel-news.com/laravel-castable-data-transfer-object
* https://github.com/spatie/data-transfer-object

**Comment by rhysemmerson** [comment]
Sounds like an interesting talk

**Comment by gregskerman** [comment]
As a recovering Doctrine user, storing/casting back and forth between VOs is something I'd enjoy I think!

**Comment by jryd** [comment]
After a long hiatus, we're restarting the Brisbane Laravel Meetup.

If you're still interested in presenting this talk [at our next meetup](https://www.meetup.com/bne-laravel-meetup/events/296922338/) then please let us know!

In the meantime, we'll close this proposal so that we can start from a clean slate.
