### ISSUE TITLE
Talk Proposal: Building a Service Container from Scratch

### ISSUE THREAD

**Issue by jessarcher** [Brisbane-Laravel-Meetup/meetups#8]
I've been fascinated by Laravel's service container and how useful it is for quite a while now. I enjoy teaching others about it, including most recently in an [episode of my podcast with JMac (of Laravel Shift fame)](https://basecodefieldguide.com/podcast/24-demystifying-laravel-service-container/). In that episode we talked about how a primitive service container implementation could work, and I've often thought it would be interesting to actually build a basic implementation of a service container, roughly following Laravel's API, to demonstrate and demystify it for visual/practical learners.

I'm not too sure how long it would take to implement all of the features I'd like to cover, but I'm sure I could easily cover the basics and then hopefully include a few extra cool features like using it to swap implementations for mocked objects in tests, using it for dependency injection, and maybe using it to implement the singleton pattern.

**Comment by jryd** [comment]
As someone who uses the service container daily, but hasn't ever really dived into a practical look at _how_ it works - this would be pretty cool!

**Comment by gregskerman** [comment]
@jessarcher I've marked this one as talk scheduled

**Comment by jryd** [comment]
A recording of this talk can be found here; https://youtu.be/sMYmZjfqPN0?t=3044
