### ISSUE TITLE
Talk Proposal: Building a Schema-Driven Form

### ISSUE THREAD

**Issue by jessarcher** [Brisbane-Laravel-Meetup/meetups#9]
It seems like everywhere I've worked, there has been a requirement for schema-driven forms. In other words, a form that is configurable in some way, as opposed to being hard-coded HTML.

This is a pretty big topic, especially when you start to look at things like validation, storage of the dynamic data, versioning, displaying a read-only versions of the data, and reporting. Not to mention the differences you may encounter when building a server-rendered version compared with an SPA version. I've even had to build implementations that auto-saved drafts that could later be resumed.

All that is to say I'm not sure what the format of this talk would be yet, or whether I have the appetite to fully distill my experiences into "from scratch" type talk, or whether it might be more of a code-walkthrough of an existing solution. If there is interest in this topic, it might be nice to get an idea of the sort of talk and content that people would be most interested in.

**Comment by jryd** [comment]
This sounds pretty cool, but I must agree that it's a big topic and once you start going down the rabbit hole I'm sure there's a tonne of edge cases.

I'd be interested in hearing:
* How you go about editing and storing the configuration
* How you use this to hydrate a form on the frontend
* How you then validate submissions of the form (how do you support custom rules?)
* How you store the submission
* How you reconcile stored versions to previously saved versions of the form configuration (say I make a submission when there is 5 fields, but there are now 7 in the latest version of the form)

**Comment by gregskerman** [comment]
Its a big rabbit hole I'll agree. We've gone down this path in a big crazy way over here - but I think covering the basics would be good, leave the rest as an exercise for the reader or a Part 2...

**Comment by jryd** [comment]
After a long hiatus, we're restarting the Brisbane Laravel Meetup.

If you're still interested in presenting this talk [at our next meetup](https://www.meetup.com/bne-laravel-meetup/events/296922338/) then please let us know!

In the meantime, we'll close this proposal so that we can start from a clean slate.
